apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  type: LoadBalancer # Use LoadBalancer if exposing directly to the internet on Cloud providers
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080